import os
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv()

# Initialize OpenAI client
client = OpenAI()

def generate_answer(question: str, context_chunks: list[str]) -> str:
    """
    Generate an answer from the retrieved context using LLM.

    Args:
        question (str): The user query.
        context_chunks (list[str]): Retrieved relevant text chunks.

    Returns:
        str: Answer generated by the LLM.
    """
    # Join all chunks into a single context string
    context_text = "\n\n".join(context_chunks)

    # Create the prompt template
    prompt = f"""
You are a helpful assistant that answers questions based only on the provided context. 

Context:
{context_text}

Question:
{question}

Instructions:
- Use the context above to answer the question accurately.
- If the context does not contain enough information to answer the question, or the question is unrelated to the context, respond with: "I am sorry, this is out of my scope of knowledge."
- Do not make assumptions or provide information not present in the context.

Answer:
"""

    # Call OpenAI Chat API
    response = client.chat.completions.create(
        model="gpt-4o-mini",   # or "gpt-5-mini"
        messages=[
            {"role": "system", "content": "You are a helpful AI that answers questions based on the given context."},
            {"role": "user", "content": prompt},
        ],
        temperature=0.3  # low temperature → more factual answers
    )

    # Extract and return the answer
    return response.choices[0].message.content.strip()


# # Example usage (manual test)
# if __name__ == "__main__":
#     generate_answer(question, sample_chunks)
    # Simulated retrieved chunks (normally from retrieve_chunks function)
    # sample_chunks = [
    #     "Python is a programming language often used for AI and data science.",
    #     "It supports multiple libraries such as NumPy, Pandas, and TensorFlow."
    # ]
    # question = "What is Python mainly used for?"
    # answer = generate_answer(question, sample_chunks)
    # print("Answer:", answer)
